version: "3.5"

services:
  web:
    image: nstore.web
    container_name: nstore.web
    ports:
      - 5050:5000
    networks:
      - nstore

networks:
  nstore:
    name: nstore-network
    external: true